### ISSUE TITLE
Cannot install the package

### ISSUE THREAD

**Issue by neylsoncrepalde** [wilsonrljr/sysidentpy#39]
Hello. I am not able to install the package right now. 

Steps/code to reproduce:
On the terminal, I am running

```bash
pip install sysidentpy
```
and I get

```
Collecting sysidentpy
  Using cached https://files.pythonhosted.org/packages/b3/9b/20dde4808c7f81badaecd84f112edd161f989b94f1dc84401acda6c49ae2/sysidentpy-0.1.1.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\neylson - a3data\testepython\novoenv\scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Neylson - A3Data\\AppData\\Local\\Temp\\pip-install-donew4o8\\sysidentpy\\setup.py'"'"'; __file__='"'"'C:\\Users\\Neylson - A3Data\\AppData\\Local\\Temp\\pip-install-donew4o8\\sysidentpy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\Users\Neylson - A3Data\AppData\Local\Temp\pip-install-donew4o8\sysidentpy\
    Complete output (1 lines):
    numpy is required during installation
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

I am using Python 3.8 in a Windows 10 OS.

**Comment by renard162** [comment]
Hello. 
Try to update your numpy package before install sysidentpy.

```bash
pip install -U numpy
```

**Comment by neylsoncrepalde** [comment]
Hi @renard162 . Tried but numpy 1.19.4 is not working in windows. After I updated I could not install sysidentpy and also could not import numpy. After updating I run

```python
import numpy
```

and I get

```
** On entry to DGEBAL parameter number  3 had an illegal value
 ** On entry to DGEHRD  parameter number  2 had an illegal value
 ** On entry to DORGHR DORGQR parameter number  2 had an illegal value
 ** On entry to DHSEQR parameter number  4 had an illegal value
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Neylson - A3Data\testepython\novoenv\lib\site-packages\numpy\__init__.py", line 305, in <module>  
    _win_os_check()
  File "C:\Users\Neylson - A3Data\testepython\novoenv\lib\site-packages\numpy\__init__.py", line 302, in _win_os_check
    raise RuntimeError(msg.format(__file__)) from None
RuntimeError: The current Numpy installation ('C:\\Users\\Neylson - A3Data\\testepython\\novoenv\\lib\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86
```

If I run 

```bash
pip install sysidentpy
```

I get the exact same error described in my previous comment.

Thanks in advance.

**Comment by wilsonrljr** [comment]
Hi Neylson! There is some issues with numpy numpy 1.19.4 when using python 3.9. Its a numpy issue. What is your python version?

Besides, matplotlib do not have wheels for python 3.9 yet, so you will have a problem when you try to install sysidentpy in python 3.9 env because the two packages we are depending on are having issues with python 3.9.

 I suggest you to install python 3.8 and numpy 1.19.3 for now (everything is working using those versions).

**Comment by wilsonrljr** [comment]
Hi @neylsoncrepalde. I checked here with numpy 1.19.3 and python 3.8 and everything is ok, As I said, numpy 1.19.4 is causing the issue you described. Refer to the link below for more details:

https://github.com/numpy/numpy/issues/17726

I'm closing this issue for now, but if the suggested steps do not work for you, just let us know.
